local spec = require("spec")
local describe, it, expect = spec.describe, spec.it, spec.expect

describe("setup and :KeyHabits", function()
  it("records through setup(), reports and clears the log", function()
    local log = vim.fn.tempname()
    local root = vim.fn.fnamemodify(debug.getinfo(1, "S").source:sub(2), ":p:h:h")
    vim.cmd.source(root .. "/plugin/keyhabits.lua")
    local keyhabits = require("keyhabits")
    keyhabits.setup({ log_file = log, flush_threshold = 1 })
    expect(vim.fn.exists(":KeyHabits")):to_be(2)
    expect(keyhabits.is_recording()):to_be_true()

    vim.cmd("KeyHabits report")
    expect(vim.bo.filetype):to_be("keyhabits")
    vim.cmd.close()

    vim.cmd("KeyHabits stop")
    expect(keyhabits.is_recording()):to_be_false()
    vim.fn.writefile({ "" }, log)
    vim.cmd("KeyHabits! clear")
    expect(vim.fn.filereadable(log)):to_be(0)
  end)

  it("completes the subcommands", function()
    expect(vim.fn.getcompletion("KeyHabits r", "cmdline")):to_equal({ "report" })
  end)
end)

describe("doc/keyhabits.txt", function()
  it("builds help tags without duplicates", function()
    local root = vim.fn.fnamemodify(debug.getinfo(1, "S").source:sub(2), ":p:h:h")
    local copy = vim.fn.tempname()
    vim.fn.mkdir(copy, "p")
    vim.fn.writefile(vim.fn.readfile(root .. "/doc/keyhabits.txt"), copy .. "/keyhabits.txt")
    vim.cmd.helptags(vim.fn.fnameescape(copy))
    local tags = vim.fn.readfile(copy .. "/tags")
    expect(#tags > 10):to_be_true()
    expect(vim.fn.join(tags, "\n")):to_contain(":KeyHabits-clear")
  end)
end)
