local spec = require("spec")
local MemoryStore = require("keyhabits.infra.memory_store")
local Recorder = require("keyhabits.app.recorder")
local describe, it, expect = spec.describe, spec.it, spec.expect

describe("Recorder", function()
  it("buffers events below the threshold", function()
    local store = MemoryStore.new()
    local recorder = Recorder.new(store, 3)
    recorder:record({ n = 1 })
    recorder:record({ n = 2 })
    expect(store:read_all()):to_equal({})
  end)

  it("stores everything in order once the threshold is reached", function()
    local store = MemoryStore.new()
    local recorder = Recorder.new(store, 2)
    recorder:record({ n = 1 })
    recorder:record({ n = 2 })
    recorder:record({ n = 3 })
    expect(store:read_all()):to_equal({ { n = 1 }, { n = 2 } })
  end)

  it("stores a partial buffer on flush and never appends nothing", function()
    local store = MemoryStore.new()
    local recorder = Recorder.new(store, 10)
    recorder:flush()
    expect(store.appends):to_be(0)
    recorder:record({ n = 1 })
    recorder:flush()
    recorder:flush()
    expect(store:read_all()):to_equal({ { n = 1 } })
    expect(store.appends):to_be(1)
  end)

  it("rejects a threshold below one", function()
    expect(function()
      Recorder.new(MemoryStore.new(), 0)
    end):to_throw("at least 1")
  end)
end)
