-- The tip catalogue.
--
-- Every tip comes from the help that ships with Neovim, or with the plugin a
-- tip relies on, and names the tag it comes from, so the user can read the
-- source with :help. A tip is added only when the help backs it and the
-- better way does the same thing as the habit it replaces.
--
-- Fields of a tip:
--   id        stable name
--   sequence  Vim regexes, each matched against one whole command, in order
--   min       how many times in a row the sequence must occur; a run of a
--             tip with min 1 is a single occurrence
--   same      optional; every repeat must be the same command as the first,
--             so "fa fa" matches and "fa fb" does not
--   inside    optional; the single regex matches parts of one command, such
--             as a run of <BS> inside an Insert, and each part is one
--             occurrence
--   repeats   optional; one minimum per regex, each matched as a run of at
--             least that many commands, e.g. { 2, 1 } for two or more "j"
--             and then one or more "k"
--   fix       keys the better way takes, typed text not counted; the keys
--             saved are the keys of the run, or of the part, minus fix
--   fix_each  optional; keys the better way adds for every repeat after the
--             first, such as one ";" for each repeated "fx"
--   saves     instead of fix: the keys saved by each occurrence, for tips
--             whose commands carry an Insert of any length
--   tip       the better way, one line
--   help      the :help tag the tip comes from
--   suggests  the keys the tip recommends, as the mapping check sees them:
--             Normal mode unless prefixed "i:" (Insert) or "x:" (Visual). A
--             tip is not shown when one of them is mapped to something else
--   requires  optional; a plugin the tip needs, such as "mini.ai"
--   needs_mapping  optional; a key the tip relies on being mapped, such as
--             LazyVim's "<C-J>" for the window below, with the same mode
--             prefixes as suggests
--   source    optional; where the better way comes from, such as "LazyVim",
--             shown with the tip
--   variants  optional; better versions of the tip when a plugin or mapping
--             is there, each { requires, needs_mapping, source, tip, help,
--             suggests }; the first whose plugin and mapping are there
--             replaces tip, help and suggests
--   example   commands that show the habit; a spec checks that the tip
--             matches them, that no earlier tip takes them, and that the
--             better way saves keys
--
-- Tips are tried in order and the first match wins, so a longer habit comes
-- before a shorter one that starts the same way.

local function rep(command, times)
  local commands = {}
  for index = 1, times do
    commands[index] = command
  end
  return commands
end

return {
  {
    id = "find-then-object",
    sequence = { [=[^[fFtT][()[\]{}<>"'`]$]=], [=[^[cdy][ia][()[\]{}<>"'`bq]]=] },
    min = 1,
    saves = 2,
    requires = "mini.ai",
    tip = "Skip the f: mini.ai finds the next pair on its own, so ci( works from before the (",
    help = "MiniAi.config",
    suggests = {},
    example = { "f(", "ci(<text><Esc>" },
  },
  {
    id = "far-j",
    sequence = { [=[^\%(j\|<Down>\)$]=] },
    min = 15,
    fix = 2,
    tip = "Scroll half a screen with CTRL-D instead of holding j",
    help = "CTRL-D",
    suggests = { "<C-D>" },
    variants = {
      {
        requires = "flash.nvim",
        tip = "Jump straight to the line with s, a few letters and the label flash shows",
        help = "flash.nvim-flash.nvim-usage",
        suggests = {},
      },
    },
    example = rep("j", 15),
  },
  {
    id = "far-k",
    sequence = { [=[^\%(k\|<Up>\)$]=] },
    min = 15,
    fix = 2,
    tip = "Scroll half a screen with CTRL-U instead of holding k",
    help = "CTRL-U",
    suggests = { "<C-U>" },
    variants = {
      {
        requires = "flash.nvim",
        tip = "Jump straight to the line with s, a few letters and the label flash shows",
        help = "flash.nvim-flash.nvim-usage",
        suggests = {},
      },
    },
    example = rep("k", 15),
  },
  {
    id = "overshoot-down",
    sequence = { [=[^\%(j\|<Down>\)$]=], [=[^\%(k\|<Up>\)$]=] },
    repeats = { 2, 1 },
    min = 1,
    fix = 2,
    tip = "Read the count off the relative line numbers: 7j lands on the line, no going past and back",
    help = "'relativenumber'",
    suggests = { "j" },
    example = { "j", "j", "j", "k" },
  },
  {
    id = "overshoot-up",
    sequence = { [=[^\%(k\|<Up>\)$]=], [=[^\%(j\|<Down>\)$]=] },
    repeats = { 2, 1 },
    min = 1,
    fix = 2,
    tip = "Read the count off the relative line numbers: 7k lands on the line, no going past and back",
    help = "'relativenumber'",
    suggests = { "k" },
    example = { "k", "k", "k", "j" },
  },
  {
    id = "move-line-down",
    sequence = { [=[^dd$]=], [=[^p$]=] },
    min = 1,
    saves = 2,
    needs_mapping = "<A-j>",
    source = "LazyVim",
    tip = "Move the line down with Alt-j instead of ddp",
    help = ":move",
    suggests = {},
    example = { "dd", "p" },
  },
  {
    id = "move-line-up",
    sequence = { [=[^dd$]=], [=[^k$]=], [=[^P$]=] },
    min = 1,
    saves = 3,
    needs_mapping = "<A-k>",
    source = "LazyVim",
    tip = "Move the line up with Alt-k instead of ddkP",
    help = ":move",
    suggests = {},
    example = { "dd", "k", "P" },
  },
  {
    id = "window-move",
    sequence = { [=[^<C-W>[hjkl]$]=] },
    min = 1,
    fix = 1,
    needs_mapping = "<C-J>",
    source = "LazyVim",
    tip = "Go to the next window with CTRL-H, CTRL-J, CTRL-K or CTRL-L instead of CTRL-W h, j, k, l",
    help = "CTRL-W_j",
    suggests = {},
    example = { "<C-W>j" },
  },
  {
    id = "blank-line-below-in-place",
    sequence = { [=[^o<Esc>$]=], [=[^k$]=] },
    min = 1,
    saves = 1,
    tip = "Add an empty line below and stay on this one with ]<Space> instead of o<Esc>k",
    help = "]<Space>",
    suggests = { "]<Space>" },
    example = { "o<Esc>", "k" },
  },
  {
    id = "blank-line-above-in-place",
    sequence = { [=[^O<Esc>$]=], [=[^j$]=] },
    min = 1,
    saves = 1,
    tip = "Add an empty line above and stay on this one with [<Space> instead of O<Esc>j",
    help = "[<Space>",
    suggests = { "[<Space>" },
    example = { "O<Esc>", "j" },
  },
  {
    id = "back-then-change-word",
    sequence = { [=[^b$]=], [=[^dw$]=], [=[^i]=] },
    repeats = { 1, 1, 1 },
    min = 1,
    saves = 1,
    tip = "Change the word under the cursor with ciw instead of b, dw, i",
    help = "04.8",
    suggests = { "c" },
    example = { "b", "dw", "i<text><Esc>" },
  },
  {
    id = "delete-words-then-insert",
    sequence = { [=[^dw$]=], [=[^i]=] },
    repeats = { 1, 1 },
    min = 1,
    saves = 1,
    tip = "Change words in one go: cw, c2w instead of dw then i (cw keeps the space after the word)",
    help = "cw",
    suggests = { "c" },
    example = { "dw", "dw", "i<text><Esc>" },
  },
  {
    id = "end-then-append",
    sequence = { [=[^\$$]=], [=[^a]=] },
    min = 1,
    saves = 1,
    tip = "Append at the end of the line with A instead of $a",
    help = "A",
    suggests = { "A" },
    example = { "$", "a<text><Esc>" },
  },
  {
    id = "first-then-insert",
    sequence = { [=[^\^$]=], [=[^i]=] },
    min = 1,
    saves = 1,
    tip = "Insert before the first non-blank with I instead of ^i",
    help = "I",
    suggests = { "I" },
    example = { "^", "i<text><Esc>" },
  },
  {
    id = "delete-to-end-then-append",
    sequence = { [=[^\%(d\$\|D\)$]=], [=[^a]=] },
    min = 1,
    saves = 1,
    tip = "Change to the end of the line with C instead of d$a or Da",
    help = "C",
    suggests = { "C" },
    example = { "d$", "a<text><Esc>" },
  },
  {
    id = "delete-object-then-insert",
    sequence = { [=[^d[ia]\%([wWsp()b{}B"'`t\[\]>]\|<lt>\)$]=], [=[^i]=] },
    min = 1,
    saves = 1,
    tip = "Change the text object in one go: ciw instead of diw then i",
    help = "04.8",
    suggests = { "c" },
    example = { "diw", "i<text><Esc>" },
  },
  {
    id = "delete-line-then-open",
    sequence = { [=[^dd$]=], [=[^O]=] },
    min = 1,
    saves = 1,
    tip = "Replace a line with cc instead of dd then O",
    help = "cc",
    suggests = { "c" },
    example = { "dd", "O<text><Esc>" },
  },
  {
    id = "x-then-insert",
    sequence = { [=[^x$]=], [=[^i]=] },
    min = 1,
    saves = 1,
    tip = "Replace a character and start inserting with s instead of xi",
    help = "s",
    suggests = { "s" },
    example = { "x", "i<text><Esc>" },
  },
  {
    id = "up-then-open-below",
    sequence = { [=[^k$]=], [=[^A<CR>]=] },
    min = 1,
    saves = 2,
    tip = "Open a new line above with O instead of kA<CR>",
    help = "O",
    suggests = { "O" },
    example = { "k", "A<CR><text><Esc>" },
  },
  {
    id = "down-to-first-non-blank",
    sequence = { [=[^j$]=], [=[^[\^_]$]=] },
    min = 1,
    saves = 1,
    tip = "Go to the first non-blank of the next line with + instead of j^",
    help = "+",
    suggests = { "+" },
    example = { "j", "^" },
  },
  {
    id = "up-to-first-non-blank",
    sequence = { [=[^k$]=], [=[^[\^_]$]=] },
    min = 1,
    saves = 1,
    tip = "Go to the first non-blank of the line above with - instead of k^",
    help = "-",
    suggests = { "-" },
    example = { "k", "^" },
  },
  {
    id = "left-then-delete",
    sequence = { [=[^h$]=], [=[^x$]=] },
    min = 1,
    saves = 1,
    tip = "Delete the character before the cursor with X instead of hx",
    help = "X",
    suggests = { "X" },
    example = { "h", "x" },
  },
  {
    id = "left-then-append",
    sequence = { [=[^h$]=], [=[^a]=] },
    min = 1,
    saves = 1,
    tip = "Insert before the cursor with i instead of ha",
    help = "i",
    suggests = { "i" },
    example = { "h", "a<text><Esc>" },
  },
  {
    id = "right-then-insert",
    sequence = { [=[^l$]=], [=[^i]=] },
    min = 1,
    saves = 1,
    tip = "Append after the cursor with a instead of li",
    help = "a",
    suggests = { "a" },
    example = { "l", "i<text><Esc>" },
  },
  {
    id = "delete-motion-then-insert",
    sequence = { [=[^d\%([eEbB]\|[tTfF].\)$]=], [=[^i]=] },
    min = 1,
    saves = 1,
    tip = "Change with the motion in one go: ce, ct) instead of de then i",
    help = "c",
    suggests = { "c" },
    example = { "dt)", "i<text><Esc>" },
  },
  {
    id = "delete-word-then-space",
    sequence = { [=[^diw$]=], [=[^x$]=] },
    min = 1,
    saves = 1,
    tip = "Delete a word and the space after it with daw instead of diwx",
    help = "aw",
    suggests = { "d" },
    example = { "diw", "x" },
  },
  {
    id = "dot-after-dd",
    sequence = { [=[^dd$]=], [=[^\.$]=], [=[^\.$]=] },
    min = 1,
    fix = 3,
    tip = "Delete several lines at once with a count: 3dd instead of dd..",
    help = "dd",
    suggests = { "d" },
    example = { "dd", ".", "." },
  },
  {
    id = "dot-after-x",
    sequence = { [=[^x$]=], [=[^\.$]=], [=[^\.$]=] },
    min = 1,
    fix = 2,
    tip = "Delete several characters at once with a count: 3x instead of x..",
    help = "x",
    suggests = { "x" },
    example = { "x", ".", "." },
  },
  {
    id = "dot-after-dw",
    sequence = { [=[^dw$]=], [=[^\.$]=], [=[^\.$]=] },
    min = 1,
    fix = 3,
    tip = "Delete several words at once with a count: d3w instead of dw..",
    help = "04.1",
    suggests = { "d" },
    example = { "dw", ".", "." },
  },
  {
    id = "append-new-line",
    sequence = { [=[^A<CR>]=] },
    min = 1,
    saves = 1,
    tip = "Open a new line below with o instead of A<CR>",
    help = "o",
    suggests = { "o" },
    example = { "A<CR><text><Esc>" },
  },
  {
    id = "backspace-run",
    sequence = { [=[\%(<BS>\)\{5,}]=] },
    min = 1,
    inside = true,
    fix = 1,
    tip = "Delete the word before the cursor with CTRL-W instead of <BS><BS><BS>",
    help = "i_CTRL-W",
    suggests = { "i:<C-W>" },
    example = { "a<text><BS><BS><BS><BS><BS><text><Esc>" },
  },
  {
    id = "insert-left-run",
    sequence = { [=[\%(<Left>\)\{4,}]=] },
    min = 1,
    inside = true,
    fix = 2,
    tip = "Move back by words in Insert mode with <C-Left> instead of <Left>",
    help = "i_<C-Left>",
    suggests = { "i:<C-Left>" },
    example = { "a<text><Left><Left><Left><Left><text><Esc>" },
  },
  {
    id = "insert-right-run",
    sequence = { [=[\%(<Right>\)\{4,}]=] },
    min = 1,
    inside = true,
    fix = 2,
    tip = "Move forward by words in Insert mode with <C-Right> instead of <Right>",
    help = "i_<C-Right>",
    suggests = { "i:<C-Right>" },
    example = { "a<text><Right><Right><Right><Right><text><Esc>" },
  },
  {
    id = "repeated-j",
    sequence = { [=[^\%(j\|<Down>\)$]=] },
    min = 4,
    fix = 2,
    tip = "Give the motion a count instead of repeating j: 5j",
    help = "count",
    suggests = { "j" },
    example = rep("j", 4),
  },
  {
    id = "repeated-k",
    sequence = { [=[^\%(k\|<Up>\)$]=] },
    min = 4,
    fix = 2,
    tip = "Give the motion a count instead of repeating k: 5k",
    help = "count",
    suggests = { "k" },
    example = rep("k", 4),
  },
  {
    id = "far-l",
    sequence = { [=[^\%(l\|<Right>\|<Space>\)$]=] },
    min = 8,
    fix = 2,
    tip = "Jump to a character further along the line with f{char}",
    help = "03.3",
    suggests = { "f" },
    variants = {
      {
        requires = "flash.nvim",
        tip = "Jump with f{char}: flash highlights the matches, and f again goes to the next one",
        help = "flash.nvim-flash.nvim-usage",
        suggests = {},
      },
    },
    example = rep("l", 8),
  },
  {
    id = "far-h",
    sequence = { [=[^\%(h\|<Left>\|<BS>\)$]=] },
    min = 8,
    fix = 2,
    tip = "Jump back to a character on the line with F{char}",
    help = "03.3",
    suggests = { "F" },
    variants = {
      {
        requires = "flash.nvim",
        tip = "Jump back with F{char}: flash highlights the matches, and F again goes to the next one",
        help = "flash.nvim-flash.nvim-usage",
        suggests = {},
      },
    },
    example = rep("h", 8),
  },
  {
    id = "repeated-l",
    sequence = { [=[^\%(l\|<Right>\|<Space>\)$]=] },
    min = 4,
    fix = 2,
    tip = "Move by words with w or e instead of repeating l",
    help = "word-motions",
    suggests = { "w", "e" },
    example = rep("l", 4),
  },
  {
    id = "repeated-h",
    sequence = { [=[^\%(h\|<Left>\|<BS>\)$]=] },
    min = 4,
    fix = 2,
    tip = "Move back by words with b instead of repeating h",
    help = "word-motions",
    suggests = { "b" },
    example = rep("h", 4),
  },
  {
    id = "far-w",
    sequence = { [=[^w$]=] },
    min = 8,
    fix = 4,
    tip = "Search for the word with /word instead of stepping with w",
    help = "03.8",
    suggests = { "/" },
    variants = {
      {
        requires = "flash.nvim",
        tip = "Jump to the word with s, its first letters and the label flash shows",
        help = "flash.nvim-flash.nvim-usage",
        suggests = {},
      },
    },
    example = rep("w", 8),
  },
  {
    id = "far-b",
    sequence = { [=[^b$]=] },
    min = 8,
    fix = 4,
    tip = "Search back for the word with ?word instead of stepping with b",
    help = "?",
    suggests = { "?" },
    variants = {
      {
        requires = "flash.nvim",
        tip = "Jump back to the word with s, its first letters and the label flash shows",
        help = "flash.nvim-flash.nvim-usage",
        suggests = {},
      },
    },
    example = rep("b", 8),
  },
  {
    id = "repeated-w",
    sequence = { [=[^w$]=] },
    min = 4,
    fix = 2,
    tip = "Give the word motion a count instead of repeating w: 3w",
    help = "03.1",
    suggests = { "w" },
    example = rep("w", 4),
  },
  {
    id = "repeated-b",
    sequence = { [=[^b$]=] },
    min = 4,
    fix = 2,
    tip = "Give the word motion a count instead of repeating b: 3b",
    help = "03.1",
    suggests = { "b" },
    example = rep("b", 4),
  },
  {
    id = "repeated-e",
    sequence = { [=[^e$]=] },
    min = 4,
    fix = 2,
    tip = "Give the word motion a count instead of repeating e: 3e",
    help = "03.1",
    suggests = { "e" },
    example = rep("e", 4),
  },
  {
    id = "repeated-W",
    sequence = { [=[^W$]=] },
    min = 4,
    fix = 2,
    tip = "Give the WORD motion a count instead of repeating W: 3W",
    help = "W",
    suggests = { "W" },
    example = rep("W", 4),
  },
  {
    id = "repeated-B",
    sequence = { [=[^B$]=] },
    min = 4,
    fix = 2,
    tip = "Give the WORD motion a count instead of repeating B: 3B",
    help = "B",
    suggests = { "B" },
    example = rep("B", 4),
  },
  {
    id = "repeated-E",
    sequence = { [=[^E$]=] },
    min = 4,
    fix = 2,
    tip = "Give the WORD motion a count instead of repeating E: 3E",
    help = "E",
    suggests = { "E" },
    example = rep("E", 4),
  },
  {
    id = "repeated-ge",
    sequence = { [=[^ge$]=] },
    min = 3,
    fix = 3,
    tip = "Give ge a count instead of repeating it: 3ge",
    help = "ge",
    suggests = { "ge" },
    example = rep("ge", 3),
  },
  {
    id = "repeated-gE",
    sequence = { [=[^gE$]=] },
    min = 3,
    fix = 3,
    tip = "Give gE a count instead of repeating it: 3gE",
    help = "gE",
    suggests = { "gE" },
    example = rep("gE", 3),
  },
  {
    id = "repeated-paragraph-forward",
    sequence = { [=[^}$]=] },
    min = 3,
    fix = 2,
    tip = "Move several paragraphs at once with a count: 3}",
    help = "}",
    suggests = { "}" },
    example = rep("}", 3),
  },
  {
    id = "repeated-paragraph-back",
    sequence = { [=[^{$]=] },
    min = 3,
    fix = 2,
    tip = "Move back several paragraphs at once with a count: 3{",
    help = "{",
    suggests = { "{" },
    example = rep("{", 3),
  },
  {
    id = "repeated-sentence-forward",
    sequence = { [=[^)$]=] },
    min = 3,
    fix = 2,
    tip = "Move several sentences at once with a count: 3)",
    help = ")",
    suggests = { ")" },
    example = rep(")", 3),
  },
  {
    id = "repeated-sentence-back",
    sequence = { [=[^($]=] },
    min = 3,
    fix = 2,
    tip = "Move back several sentences at once with a count: 3(",
    help = "(",
    suggests = { "(" },
    example = rep("(", 3),
  },
  {
    id = "repeated-plus",
    sequence = { [=[^\%(+\|<CR>\)$]=] },
    min = 4,
    fix = 2,
    tip = "Move several lines to the first non-blank with a count: 5+",
    help = "+",
    suggests = { "+" },
    example = rep("+", 4),
  },
  {
    id = "repeated-minus",
    sequence = { [=[^-$]=] },
    min = 4,
    fix = 2,
    tip = "Move several lines up to the first non-blank with a count: 5-",
    help = "-",
    suggests = { "-" },
    example = rep("-", 4),
  },
  {
    id = "repeated-display-down",
    sequence = { [=[^\%(gj\|g<Down>\)$]=] },
    min = 4,
    fix = 3,
    tip = "Give gj a count instead of repeating it: 5gj",
    help = "gj",
    suggests = { "gj" },
    example = rep("gj", 4),
  },
  {
    id = "repeated-display-up",
    sequence = { [=[^\%(gk\|g<Up>\)$]=] },
    min = 4,
    fix = 3,
    tip = "Give gk a count instead of repeating it: 5gk",
    help = "gk",
    suggests = { "gk" },
    example = rep("gk", 4),
  },
  {
    id = "repeated-next-match",
    sequence = { [=[^n$]=] },
    min = 4,
    fix = 2,
    tip = "Skip ahead several matches at once with a count: 3n",
    help = "n",
    suggests = { "n" },
    variants = {
      {
        requires = "flash.nvim",
        needs_mapping = "c:<C-S>",
        source = "flash.nvim in LazyVim",
        tip = "While typing a / search, press CTRL-S: flash labels every match, so you jump straight to the one you want",
        help = "flash.nvim-flash.nvim-usage",
        suggests = {},
      },
    },
    example = rep("n", 4),
  },
  {
    id = "repeated-previous-match",
    sequence = { [=[^N$]=] },
    min = 4,
    fix = 2,
    tip = "Skip back several matches at once with a count: 3N",
    help = "N",
    suggests = { "N" },
    example = rep("N", 4),
  },
  {
    id = "repeated-star",
    sequence = { [=[^\*$]=] },
    min = 3,
    fix = 2,
    tip = "Jump to the third match of the word at once: 3*",
    help = "star",
    suggests = { "*" },
    example = rep("*", 3),
  },
  {
    id = "repeated-hash",
    sequence = { [=[^#$]=] },
    min = 3,
    fix = 2,
    tip = "Jump back to the third match of the word at once: 3#",
    help = "#",
    suggests = { "#" },
    example = rep("#", 3),
  },
  {
    id = "repeated-semicolon",
    sequence = { [=[^;$]=] },
    min = 4,
    fix = 2,
    tip = "Give ; a count instead of repeating it: 3;",
    help = ";",
    suggests = { ";" },
    example = rep(";", 4),
  },
  {
    id = "repeated-comma",
    sequence = { [=[^,$]=] },
    min = 4,
    fix = 2,
    tip = "Give , a count instead of repeating it: 3,",
    help = ",",
    suggests = { "," },
    example = rep(",", 4),
  },
  {
    id = "repeated-page-forward",
    sequence = { [=[^\%(<C-F>\|<PageDown>\)$]=] },
    min = 3,
    fix = 2,
    tip = "Scroll several pages at once with a count: 3 CTRL-F",
    help = "CTRL-F",
    suggests = { "<C-F>" },
    example = rep("<C-F>", 3),
  },
  {
    id = "repeated-page-back",
    sequence = { [=[^\%(<C-B>\|<PageUp>\)$]=] },
    min = 3,
    fix = 2,
    tip = "Scroll back several pages at once with a count: 3 CTRL-B",
    help = "CTRL-B",
    suggests = { "<C-B>" },
    example = rep("<C-B>", 3),
  },
  {
    id = "repeated-jump-older",
    sequence = { [=[^<C-O>$]=] },
    min = 3,
    fix = 2,
    tip = "Go back several jumps at once with a count: 3 CTRL-O",
    help = "CTRL-O",
    suggests = { "<C-O>" },
    example = rep("<C-O>", 3),
  },
  {
    id = "repeated-jump-newer",
    sequence = { [=[^<Tab>$]=] },
    min = 3,
    fix = 2,
    tip = "Go forward several jumps at once with a count: 3 CTRL-I",
    help = "CTRL-I",
    suggests = { "<Tab>" },
    example = rep("<Tab>", 3),
  },
  {
    id = "repeated-change-older",
    sequence = { [=[^g;$]=] },
    min = 3,
    fix = 3,
    tip = "Go back several changes at once with a count: 3g;",
    help = "g;",
    suggests = { "g;" },
    example = rep("g;", 3),
  },
  {
    id = "repeated-change-newer",
    sequence = { [=[^g,$]=] },
    min = 3,
    fix = 3,
    tip = "Go forward several changes at once with a count: 3g,",
    help = "g,",
    suggests = { "g," },
    example = rep("g,", 3),
  },
  {
    id = "repeated-next-spelling",
    sequence = { [=[^\]s$]=] },
    min = 3,
    fix = 3,
    tip = "Skip several misspelled words at once with a count: 3]s",
    help = "]s",
    suggests = { "]s" },
    example = rep("]s", 3),
  },
  {
    id = "repeated-previous-spelling",
    sequence = { [=[^\[s$]=] },
    min = 3,
    fix = 3,
    tip = "Skip back several misspelled words at once with a count: 3[s",
    help = "[s",
    suggests = { "[s" },
    example = rep("[s", 3),
  },
  {
    id = "repeated-next-diff",
    sequence = { [=[^\]c$]=] },
    min = 3,
    fix = 3,
    tip = "Skip several diff changes at once with a count: 3]c",
    help = "]c",
    suggests = { "]c" },
    example = rep("]c", 3),
  },
  {
    id = "repeated-previous-diff",
    sequence = { [=[^\[c$]=] },
    min = 3,
    fix = 3,
    tip = "Skip back several diff changes at once with a count: 3[c",
    help = "[c",
    suggests = { "[c" },
    example = rep("[c", 3),
  },
  {
    id = "repeated-next-section",
    sequence = { [=[^\]\]$]=] },
    min = 3,
    fix = 3,
    tip = "Move several sections at once with a count: 3]]",
    help = "]]",
    suggests = { "]]" },
    example = rep("]]", 3),
  },
  {
    id = "repeated-previous-section",
    sequence = { [=[^\[\[$]=] },
    min = 3,
    fix = 3,
    tip = "Move back several sections at once with a count: 3[[",
    help = "[[",
    suggests = { "[[" },
    example = rep("[[", 3),
  },
  {
    id = "repeated-scroll-left",
    sequence = { [=[^zh$]=] },
    min = 4,
    fix = 3,
    tip = "Scroll the view several columns at once with a count: 5zh",
    help = "zh",
    suggests = { "zh" },
    example = rep("zh", 4),
  },
  {
    id = "repeated-scroll-right",
    sequence = { [=[^zl$]=] },
    min = 4,
    fix = 3,
    tip = "Scroll the view several columns at once with a count: 5zl",
    help = "zl",
    suggests = { "zl" },
    example = rep("zl", 4),
  },
  {
    id = "repeated-previous-tab",
    sequence = { [=[^gT$]=] },
    min = 3,
    fix = 3,
    tip = "Go back several tab pages at once with a count: 3gT",
    help = "gT",
    suggests = { "gT" },
    example = rep("gT", 3),
  },
  {
    id = "repeated-redo",
    sequence = { [=[^<C-R>$]=] },
    min = 4,
    fix = 2,
    tip = "Redo several changes at once with a count: 4 CTRL-R",
    help = "CTRL-R",
    suggests = { "<C-R>" },
    example = rep("<C-R>", 4),
  },
  {
    id = "repeated-increment",
    sequence = { [=[^<C-A>$]=] },
    min = 3,
    fix = 2,
    tip = "Add to a number in one go with a count: 5 CTRL-A",
    help = "CTRL-A",
    suggests = { "<C-A>" },
    example = rep("<C-A>", 3),
  },
  {
    id = "repeated-decrement",
    sequence = { [=[^<C-X>$]=] },
    min = 3,
    fix = 2,
    tip = "Subtract from a number in one go with a count: 5 CTRL-X",
    help = "CTRL-X",
    suggests = { "<C-X>" },
    example = rep("<C-X>", 3),
  },
  {
    id = "repeated-macro-again",
    sequence = { [=[^@@$]=] },
    min = 3,
    fix = 3,
    tip = "Replay the macro several times at once with a count: 3@@",
    help = "@@",
    suggests = { "@@" },
    example = rep("@@", 3),
  },
  {
    id = "window-taller",
    sequence = { [=[^<C-W>+$]=] },
    min = 3,
    fix = 3,
    tip = "Make the window taller in one go with a count: 5 CTRL-W +",
    help = "CTRL-W_+",
    suggests = { "<C-W>+" },
    example = rep("<C-W>+", 3),
  },
  {
    id = "window-shorter",
    sequence = { [=[^<C-W>-$]=] },
    min = 3,
    fix = 3,
    tip = "Make the window shorter in one go with a count: 5 CTRL-W -",
    help = "CTRL-W_-",
    suggests = { "<C-W>-" },
    example = rep("<C-W>-", 3),
  },
  {
    id = "window-wider",
    sequence = { [=[^<C-W>>$]=] },
    min = 3,
    fix = 3,
    tip = "Make the window wider in one go with a count: 5 CTRL-W >",
    help = "CTRL-W_>",
    suggests = { "<C-W>>" },
    example = rep("<C-W>>", 3),
  },
  {
    id = "window-narrower",
    sequence = { [=[^<C-W><lt>$]=] },
    min = 3,
    fix = 3,
    tip = "Make the window narrower in one go with a count: 5 CTRL-W <",
    help = "CTRL-W_<",
    suggests = { "<C-W><lt>" },
    example = rep("<C-W><lt>", 3),
  },
  {
    id = "repeated-macro",
    sequence = { [=[^@[a-z0-9:]$]=] },
    min = 3,
    same = true,
    fix = 3,
    tip = "Run the macro several times at once with a count: 3@a",
    help = "@",
    suggests = { "@" },
    example = rep("@a", 3),
  },
  {
    id = "repeated-indent",
    sequence = { [=[^>>$]=] },
    min = 3,
    fix = 3,
    tip = "Shift a line several times at once from Visual mode: V3>",
    help = "v_>",
    suggests = { "x:>" },
    example = rep(">>", 3),
  },
  {
    id = "repeated-unindent",
    sequence = { [=[^<lt><lt>$]=] },
    min = 3,
    fix = 3,
    tip = "Shift a line back several times at once from Visual mode: V3<",
    help = "v_<",
    suggests = { "x:<" },
    example = rep("<lt><lt>", 3),
  },
  {
    id = "repeated-find",
    sequence = { [=[^[fFtT].$]=] },
    min = 2,
    same = true,
    fix = 2,
    fix_each = 1,
    tip = "Repeat the last f, t, F or T with ; instead of typing it again",
    help = ";",
    suggests = { ";" },
    variants = {
      {
        requires = "flash.nvim",
        tip = "Press f again to repeat the jump: flash remembers the character",
        help = "flash.nvim-flash.nvim-usage",
        suggests = {},
      },
    },
    example = rep("f(", 2),
  },
  {
    id = "repeated-word-operator",
    sequence = { [=[^d[wWeEbBjk(){}]$]=] },
    min = 2,
    same = true,
    fix = 3,
    tip = "Give the operator a count instead of repeating it: d3w, d3j",
    help = "04.1",
    suggests = { "d" },
    example = rep("dw", 2),
  },
  {
    id = "repeated-x",
    sequence = { [=[^\%(x\|<Del>\)$]=] },
    min = 3,
    fix = 2,
    tip = "Delete with a count or a motion instead of repeating x: 4x, dw",
    help = "04.1",
    suggests = { "x" },
    example = rep("x", 3),
  },
  {
    id = "repeated-X",
    sequence = { [=[^X$]=] },
    min = 3,
    fix = 2,
    tip = "Give X a count instead of repeating it: 3X",
    help = "X",
    suggests = { "X" },
    example = rep("X", 3),
  },
  {
    id = "repeated-dd",
    sequence = { [=[^dd$]=] },
    min = 2,
    fix = 3,
    tip = "Give dd a count instead of repeating it: 3dd",
    help = "dd",
    suggests = { "d" },
    example = rep("dd", 2),
  },
  {
    id = "repeated-J",
    sequence = { [=[^J$]=] },
    min = 3,
    fix = 2,
    tip = "Join several lines at once with a count: 4J",
    help = "J",
    suggests = { "J" },
    example = rep("J", 3),
  },
  {
    id = "repeated-put",
    sequence = { [=[^[pP]$]=] },
    min = 3,
    same = true,
    fix = 2,
    tip = "Put several copies at once with a count: 3p",
    help = "p",
    suggests = { "p" },
    example = rep("p", 3),
  },
  {
    id = "repeated-undo",
    sequence = { [=[^u$]=] },
    min = 4,
    fix = 2,
    tip = "Undo several changes at once with a count: 4u",
    help = "u",
    suggests = { "u" },
    example = rep("u", 4),
  },
  {
    id = "repeated-scroll-down",
    sequence = { [=[^<C-E>$]=] },
    min = 4,
    fix = 2,
    tip = "Scroll several lines at once with a count: 5 CTRL-E",
    help = "CTRL-E",
    suggests = { "<C-E>" },
    example = rep("<C-E>", 4),
  },
  {
    id = "repeated-scroll-up",
    sequence = { [=[^<C-Y>$]=] },
    min = 4,
    fix = 2,
    tip = "Scroll several lines at once with a count: 5 CTRL-Y",
    help = "CTRL-Y",
    suggests = { "<C-Y>" },
    example = rep("<C-Y>", 4),
  },
  {
    id = "repeated-case",
    sequence = { [=[^\~$]=] },
    min = 3,
    fix = 2,
    tip = "Switch the case of several characters with a count: 4~",
    help = "~",
    suggests = { "~" },
    example = rep("~", 3),
  },
  {
    id = "repeated-blank-line",
    sequence = { [=[^[oO]<Esc>$]=] },
    min = 3,
    same = true,
    fix = 3,
    tip = "Open several blank lines at once with a count: 3o<Esc>",
    help = "o",
    suggests = { "o" },
    example = rep("o<Esc>", 3),
  },
  {
    id = "visual-lines-delete",
    sequence = { [=[^Vj\{2,}d$]=] },
    min = 1,
    fix = 3,
    tip = "Delete several lines with a count instead of selecting them: 3dd",
    help = "dd",
    suggests = { "d" },
    example = { "Vjjd" },
  },
  {
    id = "visual-lines-yank",
    sequence = { [=[^Vj\{2,}y$]=] },
    min = 1,
    fix = 3,
    tip = "Yank several lines with a count instead of selecting them: 3yy",
    help = "yy",
    suggests = { "y" },
    example = { "Vjjy" },
  },
  {
    id = "visual-word-end-then-operate",
    sequence = { [=[^v[eE][dy]$]=] },
    min = 1,
    fix = 2,
    tip = "Apply the operator with the motion directly: de, ye",
    help = "04.1",
    suggests = { "d", "y" },
    example = { "ved" },
  },
  {
    id = "visual-lines-shift-right",
    sequence = { [=[^Vj\{2,}>$]=] },
    min = 1,
    fix = 3,
    tip = "Shift several lines with a count instead of selecting them: 3>>",
    help = ">>",
    suggests = { ">" },
    example = { "Vjj>" },
  },
  {
    id = "visual-lines-shift-left",
    sequence = { [=[^Vj\{2,}<lt>$]=] },
    min = 1,
    fix = 3,
    tip = "Shift several lines back with a count instead of selecting them: 3<<",
    help = "<<",
    suggests = { "<" },
    example = { "Vjj<lt>" },
  },
  {
    id = "visual-lines-filter",
    sequence = { [=[^Vj\{2,}=$]=] },
    min = 1,
    fix = 3,
    tip = "Re-indent several lines with a count instead of selecting them: 3==",
    help = "==",
    suggests = { "=" },
    example = { "Vjj=" },
  },
  {
    id = "visual-lines-join",
    sequence = { [=[^Vj\{2,}J$]=] },
    min = 1,
    fix = 2,
    tip = "Join several lines with a count instead of selecting them: 3J",
    help = "J",
    suggests = { "J" },
    example = { "VjjJ" },
  },
  {
    id = "visual-join-two",
    sequence = { [=[^Vj\=J$]=] },
    min = 1,
    fix = 1,
    tip = "Join two lines with J, no selection needed",
    help = "J",
    suggests = { "J" },
    example = { "VjJ" },
  },
  {
    id = "visual-lines-change",
    sequence = { [=[^Vj\{2,}c]=] },
    min = 1,
    saves = 1,
    tip = "Change several lines with a count instead of selecting them: 3cc",
    help = "cc",
    suggests = { "c" },
    example = { "Vjjc<text><Esc>" },
  },
  {
    id = "visual-to-last-line",
    sequence = { [=[^VG\%([=dy>]\|<lt>\)$]=] },
    min = 1,
    fix = 2,
    tip = "Apply the operator up to the last line directly: dG, =G",
    help = "G",
    suggests = { "G" },
    example = { "VG=" },
  },
  {
    id = "visual-to-first-line",
    sequence = { [=[^Vgg\%([=dy>]\|<lt>\)$]=] },
    min = 1,
    fix = 3,
    tip = "Apply the operator up to the first line directly: dgg, =gg",
    help = "gg",
    suggests = { "d" },
    example = { "Vggd" },
  },
  {
    id = "visual-character-delete",
    sequence = { [=[^v[dx]$]=] },
    min = 1,
    fix = 1,
    tip = "Delete one character with x instead of selecting it",
    help = "x",
    suggests = { "x" },
    example = { "vd" },
  },
  {
    id = "visual-character-change",
    sequence = { [=[^v[cs]]=] },
    min = 1,
    saves = 1,
    tip = "Replace one character and insert with s instead of selecting it",
    help = "s",
    suggests = { "s" },
    example = { "vc<text><Esc>" },
  },
  {
    id = "visual-character-replace",
    sequence = { [=[^vr.$]=] },
    min = 1,
    fix = 2,
    tip = "Replace one character with r{char} instead of selecting it",
    help = "r",
    suggests = { "r" },
    example = { "vrx" },
  },
  {
    id = "visual-character-case",
    sequence = { [=[^v\~$]=] },
    min = 1,
    fix = 1,
    tip = "Switch the case of one character with ~ instead of selecting it",
    help = "~",
    suggests = { "~" },
    example = { "v~" },
  },
  {
    id = "select-object-then-operate",
    sequence = { [=[^v[ia]\%([wWsp()b{}B"'`t\[\]>]\|<lt>\)[dy]$]=] },
    min = 1,
    fix = 3,
    tip = 'Apply the operator to the text object directly: diw, ya"',
    help = "04.8",
    suggests = { "d", "y" },
    example = { "viwd" },
  },
  {
    id = "select-object-then-change",
    sequence = { [=[^v[ia]\%([wWsp()b{}B"'`t\[\]>]\|<lt>\)c]=] },
    min = 1,
    saves = 1,
    tip = 'Change the text object directly: ciw, ci"',
    help = "04.8",
    suggests = { "c" },
    example = { 'vi"c<text><Esc>' },
  },
  {
    id = "delete-right",
    sequence = { [=[^dl$]=] },
    min = 1,
    fix = 1,
    tip = "Delete the character under the cursor with x instead of dl",
    help = "x",
    suggests = { "x" },
    example = { "dl" },
  },
  {
    id = "delete-left",
    sequence = { [=[^dh$]=] },
    min = 1,
    fix = 1,
    tip = "Delete the character before the cursor with X instead of dh",
    help = "X",
    suggests = { "X" },
    example = { "dh" },
  },
  {
    id = "change-character",
    sequence = { [=[^cl]=] },
    min = 1,
    saves = 1,
    tip = "Replace a character and start inserting with s instead of cl",
    help = "s",
    suggests = { "s" },
    example = { "cl<text><Esc>" },
  },
  {
    id = "delete-to-end",
    sequence = { [=[^d\$$]=] },
    min = 1,
    fix = 1,
    tip = "Delete to the end of the line with D instead of d$",
    help = "D",
    suggests = { "D" },
    example = { "d$" },
  },
  {
    id = "change-to-end",
    sequence = { [=[^c\$]=] },
    min = 1,
    saves = 1,
    tip = "Change to the end of the line with C instead of c$",
    help = "C",
    suggests = { "C" },
    example = { "c$<text><Esc>" },
  },
}
